insert into item (amount,inventory_code,name) values (1,543,'Java Book')
insert into item (amount,inventory_code,name) values (3,767,'Spring Boot Book')
insert into item (amount,inventory_code,name) values (3,981,'Swagger Book')
insert into item (amount,inventory_code,name) values (7,132,'REST API/JSON Book')
insert into item (amount,inventory_code,name) values (9,11,'Docker Book')
insert into item (amount,inventory_code,name) values (6,55,'Angular Book')